# Generated by Django 5.1.5 on 2025-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionvitals",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
