# Generated by Django 5.1.5 on 2025-02-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_alter_admissionvitals_recorded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="admission.patient"
            ),
        ),
        migrations.AlterField(
            model_name="admissiondiagnosis",
            name="admission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="admission.admission",
            ),
        ),
        migrations.AlterField(
            model_name="admissionvitals",
            name="admission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="admission.admission",
            ),
        ),
    ]
