# Generated by Django 5.1.5 on 2025-02-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0003_alter_admission_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="admission.patient"
            ),
        ),
    ]
