# Generated by Django 5.1.5 on 2025-02-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0005_alter_admission_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissiondiagnosis",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="admission.admission",
            ),
        ),
        migrations.AlterField(
            model_name="admissionvitals",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="admission.admission",
            ),
        ),
    ]
